### ISSUE TITLE
column names assignment error in position_heat_map when using data.table

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/glatos#107]
In GitLab by @trbinder on Dec 6, 2019, 15:42

See error message below. Error occurs when changing the names of columns LAT and LON in a data.table object to X and Y for use in the convUL function. Function works properly if you convert the data.table to a data.frame.

"convUL: For the UTM conversion, automatically detected zone 16.
convUL: Converting coordinates within the northern hemisphere.
Error in names(positions)[match(c("LON", "LAT"), names(positions))] <- c("X",  : 
  NAs are not allowed in subscripted assignments"

**Comment by chrisholbrook** [comment]
dependence of convUL was removed in earlier version. 
unit tests added in commit  0e69c04 and 2784884] include data.frame and data.table input. No issue with either input with test data.
