### ISSUE TITLE
Allow the read functions to use dataframes as input

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/glatos#126]
In GitLab by @ryangosse on Jul 14, 2020, 15:22

The functions `read_glatos_detections`, `read_otn_detections`, `read_glatos_receivers`, and `read_otn_deployments` should be able to take a dataframe/datatable/tibble as input. This wouldn't replace the current file path method, it'd just to give users another option when loading data into `glatos`.

**Comment by chrisholbrook** [comment]
Completed in version 0.8.0 new constructors `glatos_animals()`, `glatos_receivers()`, and `glatos_detections()` (and their `as_` counterparts serve this purpose.
