### ISSUE TITLE
Updating openxlsx to version 4.2.4 breaks read_glatos_workbook

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/glatos#138]
In GitLab by @trbinder on Aug 11, 2021, 18:20

Updated to newest glatos package (0.5.0) and everything worked fine, but a manual update of openxlsx from 4.2.3 to newest version (4.2.4) broke read_glatos_workbook. The error message was:

 Error: openxlsx can only read .xlsx files 

Error was conformed on both windows and mac.

**Comment by chrisholbrook** [comment]
fixed in fix-138-remove-openxlsx
