### ISSUE TITLE
WIP: Resolve "position_heat_map - kmz output works on Mac but not on Windows" - [opened]

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/glatos#159]
In GitLab by @trbinder on Feb 20, 2020, 15:05

_Merges 96-position_heat_map-kmz-output-works-on-mac-but-not-on-windows -> main_

Closes #96

**Comment by jdpye** [comment]
In GitLab by @jdpye on Nov 30, 2021, 12:39

changed target branch from `master` to `main`

**Comment by trbinder** [comment]
This error is the product of the fact that zip::zip seems to work differently on Windows and Macs. The issues is resolved by replacing the zip::zipr function call on or around line 452 with the following code, which calls the function differently depending on operating system.



if(Sys.info()['sysname']=="Darwin"){
   	zip::zip(zipfile = file.path(paste0(folder, "/", fish_pos_int,"_",
   	                                      abs_or_rel, ".kmz")),
   	           files = c(file.path(paste0(folder, "/", fish_pos_int,"_",
   	                                      abs_or_rel,".kml")),
   	                     file.path(paste0(folder, "/", fish_pos_int,"_",
   	                                      abs_or_rel,".png"))),
   	         mode="cherry-pick")
  	}else{
   	 zip::zip(zipfile = file.path(paste0(folder, "/", fish_pos_int,"_",
   	                                     abs_or_rel, ".kmz")),
   	          files = c(file.path(paste0(folder, "/", fish_pos_int,"_",
   	                                     abs_or_rel,".kml")),
   	                    file.path(paste0(folder, "/", fish_pos_int,"_",
   	                                     abs_or_rel,".png")))) 
  	}
