### ISSUE TITLE
Update spatial functions

### ISSUE THREAD

**Issue by haydento** [ocean-tracking-network/glatos#173]
crw_in_polygon function relies heavily on functions from the sp package.  sp is old and not being actively developed anymore. The crw_in_polygon function needs to be migrated over to sf package.  Although the function will still work, calling it throws a tons of warnings because sp is not completely compatible with recent breaking changes in external spatial libraries that sp calls, specifically, the move from proj.4 standard to >proj.6 standard.  The changes in the "proj" libraries impact how R handles coordinate reference systems For more information see https://inbo.github.io/tutorials/tutorials/spatial_crs_coding/ and references within.

**Comment by chrisholbrook** [comment]
fixed in glatos 0.7.0 ("sour-peaches"); commit c6ca9c1f3e540b2ddfbe6e99899b7a09f211405d.
