### ISSUE TITLE
Contribution guide instructions still refer to "gitlab" instead of "github"

### ISSUE THREAD

**Issue by haydento** [ocean-tracking-network/glatos#178]
Contribution instruction use gitlab link instead of github.  Needs updated.

**Comment by chrisholbrook** [comment]
Closing, because I see no instances of "gitlab" at https://github.com/ocean-tracking-network/glatos/wiki/contribution-guide

@haydento Let me know if I'm wrong and we can re-open.

**Comment by mhpob** [comment]
Multiple instances referencing and linking to gitlab in CONTRIBUTING.md.
https://github.com/ocean-tracking-network/glatos/blob/main/CONTRIBUTING.md
