### ISSUE TITLE
summarize_detections produces incorrect values in num_locs and locations columns

### ISSUE THREAD

**Issue by trbinder** [ocean-tracking-network/glatos#182]
<img width="629" alt="Screen Shot 2023-09-12 at 13 19 42 PM" src="https://github.com/ocean-tracking-network/glatos/assets/95298699/7c2fa2ce-991d-4031-9ef1-55407b55ddc1">

There appears to be a bug in the code that cause the location_col argument character string to be displayed in the locations column rather than a summary of locations that each fish was detected. This occurs when summ_type = "location" or "animal".

**Comment by chrisholbrook** [comment]
Fixed in glatos 0.7.2 (commit 3f0a2ee366d8c9447bf4b0bff0a1f8dbfd3819a6 ).

**Comment by chrisholbrook** [comment]
Fixed in glatos 0.7.3 (commit https://github.com/ocean-tracking-network/glatos/commit/f455938a81dc095863f5394b99e3623a387878fe). 

Reiterates #220.
