### ISSUE TITLE
POLYGON check in `make_transition` update breaks gganimate vignette

### ISSUE THREAD

**Issue by mhpob** [ocean-tracking-network/glatos#188]
[Cropping the Great Lakes polygon](https://github.com/ocean-tracking-network/glatos/blob/main/inst/supplemental_docs/gganimate_handout.Rmd#L92) as outlined in the gganimate handout creates a multipolygon, which causes an error in `make_transition` as the function only allows polygon WKT. Looks to have been introduced in 1852246.

https://github.com/ocean-tracking-network/glatos/blame/main/R/vis-make_transition.r#L196-L199

Is the intent to exclude multipolygons? If not, the lines could be adapted to the following:

```
if (!all(grepl('POLYGON', st_geometry_type(in_shp)))){
   stop(paste0("Input can only contain polygon data."))
}
```

That could also allow CurvePolygons which may or may not be a good thing.

**Comment by chrisholbrook** [comment]
gganimate vignette was removed in 0.8.0
