### ISSUE TITLE
`concat_list_strings` non-exported helper function defined twice

### ISSUE THREAD

**Issue by mhpob** [ocean-tracking-network/glatos#199]
- [`convert_glatos_to_att`](https://github.com/ocean-tracking-network/glatos/blob/dev/R/util-convert_glatos_to_att.r#L170-L178)
- [`convert_otn_erddap_to_att`](https://github.com/ocean-tracking-network/glatos/blob/dev/R/util-convert_otn_erddap_to_att.r#L210-L218)

**Comment by chrisholbrook** [comment]
fixed in commit e5f1fef (removed concat_list_strings() from util-convert_glatos_to_att.R)
