### ISSUE TITLE
`read_glatos_detections` coerces to data.table

### ISSUE THREAD

**Issue by mhpob** [ocean-tracking-network/glatos#200]
Tests for `read_glatos_detections` currently fail as the "correct" objects (`data(walleye_detections)` and `data(lamprey_detections)`) are of the class glatos_detections/data.frame, while importing a csv via `read_glatos_detections` returns a glatos_detections/data.table/data.frame regardless of input (data.frame, data.table, tibble).

Considering other functions attempt to conserve input class, is this the desired behavior?

**Comment by mhpob** [comment]
Tests for `read_glatos_receivers` also fail for a similar reason: `data(sample_receivers)` is not a data.table.

**Comment by chrisholbrook** [comment]
This is not the desired behavior; was introduced in v0.8.0.9000 as an unintended consequences of changes to as_glatos_detections and as_glatos_receivers. Fix will be pushed momentarily. Thanks @mhpob for the very helpful poke.

**Comment by chrisholbrook** [comment]
Fixed in v 0.8.0.9001 (7912d90d6bfb0dabfafdb2754851d42b55d1f92e). 

All tests for read_glatos_detections and read_glatos_receivers are now passing; but are still warning that "`context()` was deprecated in the 3rd edition."

**Comment by chrisholbrook** [comment]
@mhpob @jdpye Take a quick scan of https://github.com/ocean-tracking-network/glatos/commit/7912d90d6bfb0dabfafdb2754851d42b55d1f92e... I only changed a few lines in R/load-read_glatos_detections.r and R/load-read_glatos_receivers.r but git thinks every line was changed. But not in the other two files. Any idea why?

**Comment by chrisholbrook** [comment]
@mhpob @jdpye After I committed https://github.com/ocean-tracking-network/glatos/commit/7912d90d6bfb0dabfafdb2754851d42b55d1f92e, I then did a `git pull` and see this new "Style code (GHA)" commit (not made locally by me; authored by me on github?

![image](https://github.com/ocean-tracking-network/glatos/assets/9382173/f5ec120b-0073-483b-b5a1-ae6728869a61)

**Comment by mhpob** [comment]
That's the "style" GH Action that was added with the R CMD check. Takes code and adds spacing, etc. for a consistent style.

It can be turned off by deleting the file at .github/workflows/style.yml

**Comment by mhpob** [comment]
Just looked -- the stylr action happens after your original commit with a separate commit and so shouldn't affect the original. No idea why git thought you changed everything.
