### ISSUE TITLE
`fasttime` dependency/documentation is unneeded

### ISSUE THREAD

**Issue by mhpob** [ocean-tracking-network/glatos#211]
In the interest of _one less dependency_, `fasttime` was [functionally baked into `lubridate` in 2013](https://github.com/tidyverse/lubridate/pull/200) and `lubridate` doesn't seem to have recognized `option(lubridate.fasttime = TRUE)` [since around that time](https://github.com/tidyverse/lubridate/commit/95040e63074e9d8016d5f8dd3c2345d6f9e0e69f#diff-8caf551aacd1a609e0b3b4cc4ae397bcab149b97723d08e167d546fd3bae0a10L533), as well.

Fix is simple: remove the lines below and drop `fasttime` from `DESCRIPTION`. Unfortunately, there's a lot of documentation that references `fasttime::fastPOSIXct` that would require a bit more work.

Benchmarks of the respective unit tests with and without the noted lines give the same result:

[`read_otn_detections`](https://github.com/ocean-tracking-network/glatos/blob/7e2b883d9068bdf1456b9b31c47fc2ac0d7bd4a1/R/load-read_otn_detections.r#L55)
```
Unit: milliseconds
         expr     min      lq     mean   median      uq     max neval
     fasttime 16.1708 16.5407 17.51958 16.75265 17.6666 32.2774   100
  no_fasttime 16.0693 16.4321 17.58034 16.79735 17.4881 37.6090   100
```

[`read_glatos_receivers`](https://github.com/ocean-tracking-network/glatos/blob/7e2b883d9068bdf1456b9b31c47fc2ac0d7bd4a1/R/load-read_glatos_receivers.r#L82)
```
Unit: milliseconds
         expr     min      lq     mean   median      uq     max neval
     fasttime 11.4339 11.7742 12.98503 12.10125 12.6295 34.0413   100
 no_fastttime 11.3979 11.8468 12.80299 12.14700 12.5707 36.3602   100
```

[`read_glatos_detections`](https://github.com/ocean-tracking-network/glatos/blob/7e2b883d9068bdf1456b9b31c47fc2ac0d7bd4a1/R/load-read_glatos_detections.r#L18)
```
Unit: milliseconds
        expr     min       lq     mean   median       uq     max neval
    fasttime 42.3853 43.17120 47.45281 43.92875 50.82940 96.2659   100
 no_fasttime 42.5226 43.14825 47.44075 44.38395 51.65755 75.0236   100
```

[`read_otn_deployments`](https://github.com/ocean-tracking-network/glatos/blob/7e2b883d9068bdf1456b9b31c47fc2ac0d7bd4a1/R/load-read_otn_deployments.R#L64) untested due to #202

**Comment by chrisholbrook** [comment]
I support this change. FWIW, I usually go right to `lubridate::fast_strptime()`; first version of `read_glatos_detections()` would have likely used `fasttime::fastPOSIXct` directly (hence why that's prevalent in docs); but I'm not sure why we went to `parse_date_time` here instead of `fast_strptime()`.
