### ISSUE TITLE
Extract method for `vdat_list` class prevents roxygen from working

### ISSUE THREAD

**Issue by mhpob** [ocean-tracking-network/glatos#213]
On the current `dev` branch the [`vdat_list` `Extract` method](https://github.com/ocean-tracking-network/glatos/blob/dev/R/load-write_vdat_csv.r#L502-L511) prevents `devtools::document` from working and produces the following error:

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace'))

ℹ Updating glatos documentation
ℹ Loading glatos
Error in match(x, table, nomatch = 0L) : 
  no slot of name "srs" for this object of class "TransitionLayer"
Calls: suppressPackageStartupMessages ... roclet_process.roclet_namespace -> warn_missing_s3_exports -> %in%
Execution halted

Exited with status 1.
```

If I remove the code specifying the method, everything works well. If I put any code in specifying any method, it breaks.

I'm a bit confused as this has obviously not prevented someone else from running it: the S3method is exported in NAMESPACE ([this commit](https://github.com/ocean-tracking-network/glatos/commit/a383adcd9bc91afa5be25ede24494d1711115cf5#diff-b6b6854a02ae177f8860f49654ff250c1554d021ae434b6efdbe99d00bdc6055R3)); and none of the methods have anything to do with any TransitionLayers. The only thing I could find to reproduce the error is with `greatLakesTrLayer`:

```
> greatLakesTrLayer@srs
Error: no slot of name "srs" for this object of class "TransitionLayer"
```

However, the original error suggests this is an issue with `match`/`%in%` and I can't find anything using those on a `TransitionLayer` in the current code.

At a loss on this one and thinking it may just be on my computer. I apologize in advance if this is a wild goose chase.

**Comment by chrisholbrook** [comment]
I can't reproduce the issue locally on current dev branch.

**Comment by mhpob** [comment]
Thanks for checking. No idea what's going on here.

**Comment by chrisholbrook** [comment]
I just pulled dev (from a5f0b1b94af3fe488d9abb366e7a3d7109fb5da2) and now get this error when I run `devtools::check()`:

> devtools::check()
══ Documenting ═══════════════════════════════════════════════════════════════════════════════════════════════════════════
ℹ Updating glatos documentation
ℹ Loading glatos
version 0.8.0.9003 ('very-refreshing-lemonade')
Error in match(x, table, nomatch = 0L) : 
  no slot of name "srs" for this object of class "TransitionLayer"

@mhpob Any resolution on your end?

**Comment by mhpob** [comment]
No, I figured it was system specific since you weren't able to re-create it
before. It looks like the document GH Action fails with that, too.

For whatever reason, the GH Action R CMD check works (see recent runs)...
And that's directly running the CLI check that devtools wraps.

**Comment by mhpob** [comment]
I think the document GH Action runs devtools rather than the CLI program, so I'm curious if it's an issue with devtools

**Comment by mhpob** [comment]
Looks like it's actually an issue with roxygen2:: roxygenize(rocket = 'namespace'), which is what devtools wraps

**Comment by chrisholbrook** [comment]
Thanks for the tip. That lead me to discover that the issue seems unrelated to the extract method for vdat_list, but rather something about `greatLakesTrLayer` causing the issue. 

Factoring out the extract method, I can produce the error message with:

 `1 %in% list(greatLakesTrLayer)`
>Error in match(x, table, nomatch = 0L) : 
  no slot of name "srs" for this object of class "TransitionLayer"

Any value in place of 1 will produce same error. 

This seems related to the extract method only because the extract method is the only S3 method exported from this package, so when it's absent `methods %in% s3objects` doesn't get called.

Seems similar issues with RasterLayer objects have been reported (e.g., https://stackoverflow.com/questions/76074839/error-error-c-stack-usage-is-too-close-to-the-limit) but no obvious cause or solution.

@haydento I think this points to revisiting that `greatLakesTrLayer` object, maybe rebuilding it.

**Comment by chrisholbrook** [comment]
@haydento Which of these things is not like the others?
![image](https://github.com/ocean-tracking-network/glatos/assets/9382173/e192e185-768d-4baf-a683-377f9e535424)

@haydento Could you revisit this `greatLakesTrLayer` example data file, check for compatibility with contemporary R spatial packages?

Looking at `str(greatLakesTrLayer)`, I wonder if this is an sp legacy issue (also not that the warning at the bottom is the same message that triggered this issue):

![image](https://github.com/ocean-tracking-network/glatos/assets/9382173/1a48f636-a5ab-4ab6-ba06-74628958a75c)

Ideally we would also have a script in data-raw showing how this example file was created.

**Comment by mhpob** [comment]
Looking at some other issues... Was that maybe a terra SpatRaster that was forced through a function expecting a raster RasterLayer? Or created with outdated packages?

https://stackoverflow.com/questions/75489041/error-for-create-slope-cs-function-in-the-leastcostpath-package

**Comment by chrisholbrook** [comment]
Yes, I updated roxygen2 7.3.1 from 7.2.3 yesterday before I ran devtools::check, so that explanation makes sense why I didn't see that earlier.

**Comment by mhpob** [comment]
As a quick fix, it looks like you can use the Proj.4 string in `greatLakesTrLayer@crs@projargs` to fill in the SRS, which seems to hold the WKT form of a given CRS. The code below compares it against transition layers made in the examples. Note that the WKT is not exactly the same as the examples greatLakesTrLayer is specified with "+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs" and the others via EPSG:4326, which is "+proj=longlat +datum=WGS84 +no_defs ".

```
> library(glatos)
version 0.8.0.9003 ('very-refreshing-lemonade')
> library(testthat)
> 
> ## greatLakesTrLayer fails with no SRS slot
> expect_error(
+   grepl("GEOGCRS", greatLakesTrLayer@srs), 
+   "no slot of name \"srs\" for this object of class \"TransitionLayer\""
+ )
> 
> ## Others pass with SRS containing WKT string
> tst1_sf <- make_transition(great_lakes_polygon, res = c(0.1, 0.1))
Warning message:
This function is deprecated and will be removed in the next version 
> tst1_sp <- make_transition(greatLakesPoly, res = c(0.1, 0.1))
Warning messages:
1: This function is deprecated and will be removed in the next version 
2: CRS of input was not EPSG:4326, so conversion was attempted. 
> 
> expect_true(
+   grepl("GEOGCRS", tst1_sf$transition@srs)
+ )
> expect_true(
+   grepl("GEOGCRS", tst1_sp$transition@srs)
+ )
> 
> tst2_sf <- make_transition2(great_lakes_polygon, res = c(0.1, 0.1))
Making transition layer...
Done.
Warning message:
This function is deprecated and will be removed in the next version 
> tst2_sp <- make_transition2(greatLakesPoly, res = c(0.1, 0.1))
Making transition layer...
Done.
Warning message:
This function is deprecated and will be removed in the next version 
> 
> expect_true(
+   grepl("GEOGCRS", tst2_sf$transition@srs)
+ )
> expect_true(
+   grepl("GEOGCRS", tst2_sp$transition@srs)
+ )
> 
> tst3_sf <- make_transition3(great_lakes_polygon, res = c(0.1, 0.1))
Making transition layer...
Done.
> tst3_sp <- make_transition3(great_lakes_polygon, res = c(0.1, 0.1))
Making transition layer...
Done.
> 
> expect_true(
+   grepl("GEOGCRS", tst3_sf$transition@srs)
+ )
> expect_true(
+   grepl("GEOGCRS", tst3_sp$transition@srs)
+ )
> 
> ## Use greatLakesTrLayer CRS to make SRS (WKT)
> gLTL <- greatLakesTrLayer
> 
> gLTL@srs <- raster::crs(greatLakesTrLayer@crs@projargs)
> 
> substring(gLTL@srs, 1, 200)
[1] "BOUNDCRS[\n    SOURCECRS[\n        GEOGCRS[\"unknown\",\n            DATUM[\"World Geodetic System 1984\",\n                ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                    LENGTHUNIT[\"metre\",1]]"
```

**Comment by chrisholbrook** [comment]
Good call. After talking with @haydento, will update greatLakesTrLayer with `make_transition3(great_lakes_polygon, res = c(0.1, 0.1))`, add that code to data-raw and add tests following code above. Should be pushed soon.
