### ISSUE TITLE
Remove `geosphere` from dependencies

### ISSUE THREAD

**Issue by mhpob** [ocean-tracking-network/glatos#235]
`geosphere` dependency was removed in favor of `geodist` in a0209f7, but there are still places where it lingers:

`interpolate_path`
  - https://github.com/ocean-tracking-network/glatos/blob/dev/R/vis-interpolate_path.r#L501

`point_offset`
  - https://github.com/ocean-tracking-network/glatos/blob/dev/R/util-point_offset.r#L5
  - https://github.com/ocean-tracking-network/glatos/blob/dev/R/util-point_offset.r#L56

`detection_range_handout.Rmd`
  - https://github.com/ocean-tracking-network/glatos/blob/dev/inst/supplemental_docs/detection_range_handout.Rmd#L170
  - https://github.com/ocean-tracking-network/glatos/blob/dev/inst/supplemental_docs/detection_range_handout.Rmd#L191
  - https://github.com/ocean-tracking-network/glatos/blob/dev/inst/supplemental_docs/detection_range_handout.Rmd#L205

`DESCRIPTION`
  - https://github.com/ocean-tracking-network/glatos/blob/dev/DESCRIPTION#L16

CC #122 for dependency reduction tracking.

**Comment by mhpob** [comment]
`point_offset` uses `geosphere::destPoint` as its main workhorse. `point_offset` says that it is calculating the great circle distance, but it is not --`geosphere::destPoint` uses a geodesic (assuming the Earth is an ellipse) distance algorithm.

Calculating the great circle distance (assuming the Earth is a sphere) is easy and can be hard-coded without external dependency. This, however, changes results on the order of a few meters (<5m). @chrisholbrook is this an acceptable change?

The distance in meters between resulting coords according to `geodist::geodist_vec` is:

 [1]        NA      0.3730123 0.5492174 0.6980811 0.8276335 0.9698963 1.1586693
 [8] 1.3963796 1.6483109  1.8660119 2.0147364 2.0946781 2.1517980 2.2630914
[15] 2.4829321 2.7918899 3.1107809

**Comment by mhpob** [comment]
https://github.com/ocean-tracking-network/glatos/pull/236#issuecomment-2294237823

**Comment by chrisholbrook** [comment]
completed in https://github.com/ocean-tracking-network/glatos/commit/a20ca37eb87c75592db3a5ffecb65b3696ddecc7
