### ISSUE TITLE
Add column name and format checks to glatos_detections and glatos_receivers

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/glatos#78]
In GitLab by @chrisholbrook on Nov 13, 2019, 11:09

Add column name and format checks to `glatos_detections` and `glatos_receivers` to help identify issues with custom data frames (non-GLATOS and non-OTN data).

**Comment by chrisholbrook** [comment]
completed in 0.8.0; see new constructors `glatos_detections()`, `glatos_receivers()` and their validator counterparts.
