### ISSUE TITLE
position_heat_map feature requests

### ISSUE THREAD

**Issue by jdpye** [ocean-tracking-network/glatos#8]
In GitLab by @chrisholbrook on Apr 14, 2017, 16:58

to do for position_heat_map
* [x] toggle output formats (plot, png, kmz)
* [x] create kmz instead of kml
* [x] improve accuracy of conversion to grid from wgs84 decimal degrees; convert to UTM first
* [x] add argument 'output_type' to specify if output units are "absolute" or "relative"
* [x] add argument 'output_type' to specify if exporting "fish", "positions" or "intervals"
* [x] return something (raster? matrix?)

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Apr 18, 2017, 13:02

marked the task **allow user to set x and y limits** as completed

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Apr 18, 2017, 13:02

marked the task **allow output directory to be specified** as completed

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Feb 26, 2018, 14:31

marked the task **double check dependencies (raster, geosphere, plotrix)** as completed

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Feb 26, 2018, 14:32

changed title from **{-TODO positionHeatMap-}** to **{+position_heat_map feature requests+}**

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Feb 26, 2018, 14:32

changed the description

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Sep 4, 2018, 15:46

assigned to @trbinder and unassigned @chrisholbrook

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Feb 8, 2019, 16:06

marked the task **toggle output formats (plot, png, kmz)** as completed

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Feb 8, 2019, 16:06

marked the task **create kmz instead of kml** as completed

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Feb 8, 2019, 16:06

marked the task **improve accuracy of conversion to grid from wgs84 decimal degrees; convert to UTM first** as completed

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Feb 8, 2019, 16:06

marked the task **add argument 'output_type' to specify if output units are "absolute" or "relative"** as completed

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Feb 8, 2019, 16:06

marked the task **return something (raster? matrix?)** as completed

**Comment by jdpye** [comment]
In GitLab by @chrisholbrook on Feb 8, 2019, 16:21

requested features added with  2feb180c

**Comment by chrisholbrook** [comment]
completed in https://github.com/ocean-tracking-network/glatos/commit/2feb180c9d36b5578abaebdbb08dee1bd43f2af5
